name: test-build-deploy
on: [push]
env:
  PYTHON_VERSION: 3.9

jobs:
  test-infra:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}  # You can specify your desired Python version

    # - name: Install dependencies
    #   run: pip install -r requirements.txt

    - name: Run tests
      run: python -m unittest discover

  build-and-deploy-infra:
    needs: test-infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}  # You can specify your desired Python version
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-west-1
      - run: sam build
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset

    
